

create table users(
                      id int generated by default as identity primary key,
                      username varchar(30) not null unique,
                      password varchar(80) not null,
                      email varchar(50) unique
);

create table roles(
                      id int generated by default as identity primary key ,
                      name varchar(50) not null
);

create table users_roles(
                            user_id int references users(id) on delete cascade ,
                            role_id int references roles(id) on delete cascade ,
                            primary key (user_id,role_id)
)



